### ISSUE TITLE
Train PartiallyReversibleUNet on brats dataset

### ISSUE THREAD

**Issue by JunMa11** [RobinBruegger/PartiallyReversibleUnet#1]
Dear @RobinBruegger ,

Thanks for making the great work publically available.

Could you give guidance on how to train `PartiallyReversibleUNet ` on brats dataset?

Best,
Jun

**Comment by RobinBruegger** [comment]
Dear Jun,

Thanks for your interest! I've added some documentation on how to install and use the codebase. Please let me know if you run into any problems.

Best,
Robin

**Comment by John1231983** [comment]
@JunMa11 : Have you success to train on brats 2018 ? I got the error when run python train.py
```
Segmentation fault (core dumped)

```
I think it is better to remove commt.ml in training if we run it in server

**Comment by John1231983** [comment]
For got it. It is problem of from matplotlib import pyplot as plt. I fixed it by 
```
import matplotlib as mpl
mpl.use('TkAgg')  # or whatever other backend that you want
import matplotlib.pyplot as plt
```
