### ISSUE TITLE
How many GB to run your code?

### ISSUE THREAD

**Issue by John1231983** [RobinBruegger/PartiallyReversibleUnet#2]
I have 11GB on my PC and I cannot run your training process. Could you tell me how to reduce the images size to run your code. I want to run with image size of 128x128x128

**Comment by RobinBruegger** [comment]
Hi John

I trained with a 12GB graphics card. If you feed the images in at 128x128x128 however, 11GB should be more than enough

**Comment by John1231983** [comment]
The current code run with full size or 128x128x128? If it runs with full size, how to set up to run with 128x128x128 because my gpu is not enough?

**Comment by thinkInJava33** [comment]
> The current code run with full size or 128x128x128? If it runs with full size, how to set up to run with 128x128x128 because my gpu is not enough

the current code run with full size. if you want to run with 128 128 128. you should set  `RANDOM_CROP` in the experiment file.
