### ISSUE TITLE
CUDA out of memory 

### ISSUE THREAD

**Issue by thinkInJava33** [RobinBruegger/PartiallyReversibleUnet#5]
i ran train.py with gtx1080ti 11GB and failed. how to solve the problem of memory usage.

**Comment by RobinBruegger** [comment]
@thinkInJava33: For the full images, 12GB are needed. As you have already noticed, you can set `RANDOM_CROP` in the experiment file to train with smaller volumes (and therefore less GPU memory)

**Comment by thinkInJava33** [comment]
@RobinBruegger  
how long does the traning take?

**Comment by RobinBruegger** [comment]
@thinkInJava33 Depends on your GPU and the model you train. I don't remember exactly, but I think it was between 2 and ~5 days, depending on the model. I trained on a TITAN Xp
