### ISSUE TITLE
About Dice Loss

### ISSUE THREAD

**Issue by Pamikk** [RobinBruegger/PartiallyReversibleUnet#6]
Thanks for sharing code, your paper is amazing. I am currently working about it for my course project and I noticed that bratsDiceLoss in bratsUtils.py was divided 5. I thought there was not much influence will be resulted by changing the denominator but  I am still wondering if there any meaning of setting this denominator?

Thank you very much.

**Comment by RobinBruegger** [comment]
Hi @snilloO 
You are right, this denominator does not have much effect. I originally used it because I summed 5 losses. However, when using the Adam optimizer, it is just a constant factor and not that important anyways.
